### PR TITLE
nvisii_data_gen: Add missing textures + requirements

### PR DESCRIPTION
**Pull request by mintar**

### CODE REVIEW

**Comment by TontonTremblay** [comment]
Thank you Martin, this was fast, I forgot that I had to force add them. Thank you for the update.

**Comment by TontonTremblay** [comment]
Also you were very quick :P amazing :P

**Comment by mintar** [comment]
I saw your comment on the other issue and just *had* to try this. It's awesome, thanks for uploading it! :)

**Comment by TontonTremblay** [comment]
I had these scripts ready a while back, but never really got around publishing them. I am glad you like it, thank you.

**Pull request merged**
