### PR TITLE
Fix markers flickering in RViz

### LINKED ISSUE #119: ROS visualization in RViz
Hello,

I am using  ROS Rviz to visualize  the weight I have trained. Currently, the bounding box can accurately mark the position of the target object, but the displayed cube will flicker and shake.
I would like to ask what method can be **avoid flickering**.
Look forward to your reply. Thank you!

### PR DESCRIPTION
**Pull request by mintar**
Fixes #119 .

This pull request is not tested yet because I don't have access to the hardware at the moment. Please test before merging.

### CODE REVIEW

**Comment by Tingcccc** [comment]
Change **marker.action = Marker.DELETEALL** to **Marker.DELETE**  that can fix the flickering problem in RViz.

**Comment by mintar** [comment]
> Change marker.action = Marker.DELETEALL to Marker.DELETE that can fix the flickering problem in RViz.

Nope, that doesn't work. See [my comment on #119](https://github.com/NVlabs/Deep_Object_Pose/issues/119#issuecomment-625235432).

**Comment by TontonTremblay** [comment]
I also do not have access to testing material. Thank you for quickly answering our friend on this! I will merge once it is tested.

**Comment by Tingcccc** [comment]
I have an additional question, how do I display the 3D cube and the bounding box on the same image?
Thank you.

**Comment by mintar** [comment]
> I have an additional question, how do I display the 3D cube and the bounding box on the same image?

Answered at #119.

**Comment by mintar** [comment]
I have just successfully tested this PR, and it is ready for merging.

**Pull request merged**
