### PR TITLE
Readme and FAQ for training script to avoid duplicate issues.

### PR DESCRIPTION
**Pull request by saratrajput**
Some general guidelines to start training and FAQ to avoid duplicate issues.

### CODE REVIEW

**Comment by TontonTremblay** [comment]
Sorry for the late reply (I am out of town currently). I have been wondering about the best place to put such FAQ, would it be better located in the wiki page of the github? Do you have thoughts?

**Comment by mintar** [comment]
For the FAQ, I think using the wiki is a great idea.

In general, if there's documentation that's closely linked to the code (such as a README with installation instructions and descriptions of various parameters), I strongly prefer it to be inside the repository itself - that way you always get the correct version of the documentation for the version of the code you've checked out. But I guess the FAQ will be edited often, and the edits won't be linked to code commits, so it would be distracting to have FAQ commits intermingled with the code commits in the git history.

**Comment by saratrajput** [comment]
I agree with placing FAQs in the wiki. But I wonder as the main README suggests training code is unsupported if the FAQs should just remain in the readme of training code.

**Comment by TontonTremblay** [comment]
Even though we do not really support the code, the discussion that is happening in the issues can be quite useful to new users. I think adding them to a FAQ type of wiki is kind of needed.

**Comment by saratrajput** [comment]
I agree. Makes sense. So would you like me to edit it and remove FAQs? And are pull requests for wiki enabled?

**Comment by TontonTremblay** [comment]
Could you change your PR for a link to the wiki and please add your text to the wiki, if you can do a PR on the wiki. Otherwise I will add your text. Thank you so much for your PR btw.

**Comment by saratrajput** [comment]
Sure. About the *Steps to start training*, should I leave them in the README or should I move them to the wiki too?

**Comment by saratrajput** [comment]
@TontonTremblay I'm trying to follow this guide to add the wiki: https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html.
But I can't clone the original repo's wiki, since I don't think it exists.

**Comment by TontonTremblay** [comment]
This is my bad, I am so sorry about this. I should have created the page a while ago. Let me know if this is ok?

**Comment by saratrajput** [comment]
No worries. I'll generate a PR soon.

**Comment by saratrajput** [comment]
So I followed the steps from: https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

**Comment by saratrajput** [comment]
@TontonTremblay is this still required? Or would you like me to make any changes?

**Comment by TontonTremblay** [comment]
I ended up doing it manually. Thank you so much, and I am so sorry I did not deal with this earlier.

**Pull request closed without merging**
